# Generated by Django 5.2.7 on 2025-10-23 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cnpj", models.CharField(blank=True, max_length=20, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("endereco", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razao_social", models.CharField(max_length=200)),
                ("nome_fantasia", models.CharField(blank=True, max_length=200)),
                ("cpf_cnpj", models.CharField(blank=True, max_length=50)),
                ("telefone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("endereco", models.CharField(blank=True, max_length=255)),
                ("cidade_uf", models.CharField(blank=True, max_length=100)),
                ("cep", models.CharField(blank=True, max_length=20)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("previsao_entrega", models.DateField(blank=True, null=True)),
                ("solicitante", models.CharField(blank=True, max_length=200)),
                ("servicos_descricao", models.TextField(blank=True)),
                ("escopo", models.TextField(blank=True)),
                ("local_uso", models.CharField(blank=True, max_length=255)),
                ("responsavel", models.CharField(blank=True, max_length=200)),
                ("observacao", models.TextField(blank=True)),
                ("forma_pagamento", models.CharField(blank=True, max_length=100)),
                ("vencimento", models.DateField(blank=True, null=True)),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.cliente"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=50)),
                ("nome", models.CharField(max_length=150)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=50)),
                ("nome", models.CharField(max_length=200)),
                (
                    "preco",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemOrcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="core.orcamento",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.produto",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.servico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário da Empresa",
                "verbose_name_plural": "Usuários da Empresa",
                "unique_together": {("user", "empresa")},
            },
        ),
    ]
