# Generated by Django 5.2.7 on 2025-10-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_orcamento_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
