services:
  - type: web
    name: fluxxosolutions
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn fluxxosolutions.wsgi
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: fluxxosolutions.settings
